[versions]
activityVersion = "1.9.1"
agp = "8.5.0"
converterGson = "2.9.0"
converterGsonVersion = "2.11.0"
firebaseAuth = "24.0.1"
firebaseDatabase = "22.0.1"
googleServices = "4.4.4"
gradle = "7.4.2"
gradleVersion = "8.13.0"
gson = "2.13.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
kotlinxCoroutinesAndroid = "1.10.2"
loggingInterceptor = "4.12.0"
loggingInterceptorVersion = "5.3.2"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
okhttp = "5.3.0"
okhttpVersion = "4.10.0"
retrofit = "3.0.0"
retrofitVersion = "2.9.0"
slf4jAndroid = "1.7.36"
slf4jApi = "2.0.17"
firebaseAppdistributionGradle = "5.2.0"
squareupOkhttp = "4.12.0"
squareupRetrofit = "2.11.0"

[libraries]
activity-v191 = { module = "androidx.activity:activity", version.ref = "activityVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
converter-gson-v2110 = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGsonVersion" }
converter-gson-v290 = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabase" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gradle-v860 = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpVersion" }
logging-interceptor-v4120 = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
logging-interceptor-v532 = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptorVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-v4100 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
okhttp-v4120 = { module = "com.squareup.okhttp3:okhttp", version.ref = "squareupOkhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-v2110 = { module = "com.squareup.retrofit2:retrofit", version.ref = "squareupRetrofit" }
retrofit-v290 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
slf4j-android = { module = "org.slf4j:slf4j-android", version.ref = "slf4jAndroid" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
firebase-appdistribution-gradle = { group = "com.google.firebase", name = "firebase-appdistribution-gradle", version.ref = "firebaseAppdistributionGradle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

